version: '3'
services:
  client:
    platform: linux/x86_64
    build: .
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN:-http://web-server}
      NUXT_PUBLIC_TYPEWRITER: false
    ports:
      - '${CLIENT_PORT:-80}:80'
    networks:
      - chatgpt_network
    restart: always

networks:
  chatgpt_network:
    driver: bridge
